baseURL = "https://bayisca.github.io/"
languageCode = 'en-us'
title = 'Ä°smail Can AnlaÅŸ'
theme = "PaperMod"

[params]
  defaultTheme = "auto"

  # 1. TARAYICI SEKMESÄ° Ä°KONU (Favicon)
  [params.assets]
    favicon = "/logo.jpeg"
    favicon16x16 = "/logo.jpeg"
    favicon32x32 = "/logo.jpeg"

# 2. SOL ÃœSTTEKÄ° Ä°SÄ°M YANI Ä°KONU (Label Icon)
  [params.label]
    text = "Ä°smail Can"      # Logunun yanÄ±nda yazacak isim
    icon = "/logo.jpeg"       # Logonun adresi
    iconHeight = 30          # Logonun boyutu 

  # --- GÄ°RÄ°Åž KARTI ---
  [params.homeInfoParams]
    Title = "Merhaba, Ben Ä°smail ðŸ‘‹"
    Content = "Python ve PyQt6 ile masaÃ¼stÃ¼ uygulamalarÄ± geliÅŸtiriyorum. Projelerimi ve notlarÄ±mÄ± burada paylaÅŸÄ±yorum."

  # --- SOSYAL MEDYA ---
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/bayisca"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ismail-can-anla%C5%9F-270235242/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:can2323fb@gmail.com"