baseURL = "https://bayisca.github.io/"
languageCode = 'en-us'
title = 'Ä°smail Can AnlaÅŸ'
theme = "PaperMod"

[params]
  defaultTheme = "auto"

  # --- GÄ°RÄ°Å KARTI ---
  [params.homeInfoParams]
    Title = "Merhaba, Ben Ä°smail ğŸ‘‹"
    Content = "Python ve PyQt6 ile masaÃ¼stÃ¼ uygulamalarÄ± geliÅŸtiriyorum. Projelerimi ve notlarÄ±mÄ± burada paylaÅŸÄ±yorum."

  # --- SOSYAL MEDYA ---
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/bayisca"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ismail-can-anla%C5%9F-270235242/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:can2323fb@gmail.com"